version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  server:
    build:
      context: ./server/
    expose:
      - 3000
    environment:
      API_HOST: 'http://localhost:3000'
      APP_SERVER_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/srv/app/server/src
    command: npm start
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    environment:
      FRONTEND_PORT: 8080
      API_HOST: 'http://localhost:8080'
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/srv/app/client/src
    links:
      - server
    command: npm start

  mongo:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - /data:/data
    ports:
      - 27017:27017
    command: mongod
